#!/usr/bin/env python3
# requires: ruamel.yaml-0.16.12
"""
This file automatically reformats all bug descriptions in a given directory
such that they conform to a standard layout. If no argument is provided,
the script will be applied at the root of the ROBUST repository.
"""
import argparse
import os
import typing as t

from robust import yaml

DESCRIPTION = 'Automatically format ROBUST bug description files.'


def find_bug_descriptions(directory: str) -> t.Iterator[str]:
    for root, dirs, filenames in os.walk(directory):
        for filename in filenames:
            if filename.endswith('.bug'):
                full_filename = os.path.join(root, filename)
                yield full_filename


def reformat_file(filename: str) -> None:
    with open(filename, 'r') as f:
        description = yaml.load(f)
    with open(filename, 'w') as f:
        yaml.dump(description, f)


def reformat_directory(directory: str) -> None:
    for filename in find_bug_descriptions(directory):
        reformat_file(filename)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=DESCRIPTION)
    parser.add_argument('target',
                        help='path to the directory or file that should be formatted.')
    args = parser.parse_args()
    reformat_directory(args.target)
